### ISSUE TITLE
Test APIs

### ISSUE THREAD

**Issue by waseem-polus** [Waseem-Alkasbutrus/cse3311-group1#10]
### Details
- Due Date.          : **Aug 29th (For presentation)**
You are free to conduct the test however you want, but I would suggest attempting to receive info for a certain city in a test environment. This doesn't have to be within the app itself. Again, you have freedom to do this as you see fit. 

### When should this be done by?
- This should be done before the presentation 

### Subtasks
- [x] Understand how the API works and learn some of its advantages and limitations. We want to present all this info in tomorrow's presentation.
    - [ ] Based on this, we will also finally decide if we should use [The National Weather Service API](https://www.weather.gov/documentation/services-web-api) or [AccuWeather API](https://developer.accuweather.com/)
- [x] Try to get a successful API call to make sure we are able to use it.
    - [x] You can do this however you like. If you do it within the project here, please make a separate branch and test it on there.
- [x] Document findings
    - [x] Screenshots of successful or failed tests
    - [x] Update on our [slides for iteration 1](https://docs.google.com/presentation/d/1ly-_I43FjgG4fShZRuoiCs5sTKyuIFuZvyT9Sd_2LoM/edit#slide=id.p)

### People Involved
 - Person Leading: @swagat77 
 - People Helping: @PrajRana 

### Unresolved Questions
- Which API should we pick?
- What are pros and cons of either API
- How should we test those?
