### ISSUE TITLE
Project Presentation Iteration 1

### ISSUE THREAD

**Issue by Waseem-Alkasbutrus** [Waseem-Alkasbutrus/cse3311-group1#3]
### Details: **Project Presentation Iteration 1**
Due Date: **Sep 30th**
Possible Points : **100**
First iteration of our project. This includes all documentation, work product, link to repository, diagrams, and mock-up drawings we have thus far in a format that would be acceptable for a business submission.

### Subtasks
- [x] [User stories in paragraph format (1 paragraph max per story)](#5)
- [x] [UML of our choice](#4)
- [x] Updated burndown chart
- [x] Wireframes of our app
- [x] User guide documentation
- [x] GitHub link

### People Involved
 - Person Leading: @Waseem-Alkasbutrus 
 - People Helping: @christophernguyen6089 

### Unresolved Questions
- We are not sure what should be included in the user guide and how we should format it.

**Comment by Waseem-Alkasbutrus** [comment]
I think I am finished with [the iteration document](https://docs.google.com/document/d/1A80lhFnfQ1OJVQFi2Gg3zob_hNfwGz8ATDHA9A1lNK8/edit#heading=h.iyli8q99u3g). Can you guys let me know if it looks good?

**Comment by Waseem-Alkasbutrus** [comment]
Submitted to canvas. Closing issue
