### ISSUE TITLE
Create Presentation for Iteration 1

### ISSUE THREAD

**Issue by waseem-polus** [Waseem-Alkasbutrus/cse3311-group1#9]
### Parent Details: **Project Presentation Iteration 1**
Parent Task: #3 
Due Date : **Aug 29th**

### Subtask Details
Create a google slides presentation that we use for iteration 1's presentation (**Sep 29th**)

### Steps
- [x] Create slides on google drive in ``Group 1 Main Folder > Project Files > Presentations`` and call it "Iteration 1 Presentation"
- [x] Team Lead
    - [x] Update on burndown chart and progress
- [x] API Team Update
    - [x] talk about findings and if you were able to get the api working within a test environment
- [x] Design Team
    - [x] Show off mockups and layout of app. this should take the bulk of the presentation
- [x] Development (app) team
    - [x] Talk about why we chose android 9 for our app
    - [x] Discuss that you couldn't get started on the app itself because we were still working on mockups.
    - [x] Talk about anything you've learned about android studio, if any?

### People Involved
 - Person Leading: @christophernguyen6089 
 - People Helping: EVERYONE

### Unresolved Questions
- Question or problem here
